# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alid Castano
email: alidcastano.com
description: > # This is my personal blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alidcastano.com" # the base hostname & protocol for your site
twitter_username: alidcastano
github_username:  alidcastano
sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
permalink: /:title
excerpt_separator: <!--more-->

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: Alid Castano
  -
    scope:
      path: "" 
      type: "pages" 
    values:
      layout: "page"

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/alidcastano"
  resume_twitter_url:           "http://twitter.com/alidcastano"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/alidcastano"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://alidcasta.com"

# Design settings
resume_theme:                   default

