# Setup
title:               Alid Castano
tagline:             Fitness & Startups
url:                 http://alidcastano.com
analytics_id:        UA-53335201-1

# About/contact
author:
  name:                Alid Castano
  email:               alidcastano@gmail.com
  avatar:              img/avatar.jpg 
  profile-pic:         img/profile-pic.jpg

# Social Sharing
fb_admins:          https://www.facebook.com/alidcastano
fb_appid:           996066143804182
twitter_handle:     alidcastano

# Build settings
markdown:            kramdown
permalink:           /:title
sass:
  sass_dir:          _sass
  style:            :compressed
include:
  - _pages

collections:
  personal-philosophy:
    output: true
    permalink: /:title
  projects:
    output: true
    permalink: /:title
  career-capital:
    output: true
    permalink: /:title
  inner-library:
    output: true
    permalink: /:categories/:title

# Default settings
defaults:

  # posts 
  - scope:
      path: _posts/drafts 
      type: posts 
    values:
      layout: post
  - scope:
      path: _posts/thoughts
      type: posts
    values:
      layout: post
      category: thoughts
  - scope:
      path: _posts/updates 
      type: posts 
    values:
      layout: post

  # pages
  - scope:
      path: _pages 
      type: pages
    values:
      layout: page

  # projects
  - scope:
      path: _projects
      type: projects
    values:
      layout: page

  # personal-philosophy
  - scope:
      path: _personal-philosophy
      type: personal-philosophy
    values:
      layout: page
      footer: none

  # inner-library
  - scope:
      path: _inner-library/bookshelf
      type: inner-library
    values:
      layout: studbits
      category: book
      format: studbits
  - scope:
      path: _inner-library/linklog
      type: inner-library
    values:
      layout: studbits
      category: linklog
      format: studbits

  # career-capital
  - scope:
      path: _career-capital
      type: career-capital
    values:
      layout: showcase

