# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alid Castano
email: alidcastano.com
description: > # This is my personal blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alidcastano.com" # the base hostname & protocol for your site
twitter_username: alidcastano
github_username:  alidcastano
sass:
  sass_dir: _sass
  style: compressed
  
# Build settings
markdown: kramdown
permalink: /:title
excerpt_separator: <!--more-->


#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: Alid Castano
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"